import CaseEvidence from '../components/CaseEvidence'
import ResponsiveImage from '../components/ResponsiveImage'
import { Link } from 'react-router-dom'
import Breadcrumbs from '../components/Breadcrumbs'
import Seo from '../components/Seo'
import { useLang } from '../i18n/LanguageContext'
import { trackEvent } from '../lib/analytics'
import type { CaseStudy } from '../data/types'

export default function PinacelloCase({ project: c }: { project: CaseStudy }) {
  const { lang } = useLang()
  const nl = lang === 'nl'
  const steps = nl ? [
    { title: 'Aandacht die bij het product past.', body: 'Meta Ads en conversiegerichte content brengen Pinacello bij potentiële kopers. Het product, het gebruiksmoment en het aanbod vormen de rode draad.', tags: ['Meta Ads', 'Organische content'], link: '/meta-ads' },
    { title: 'Een pagina die de keuze helder maakt.', body: 'Campagne-landingspagina’s brengen aanbod, productinformatie en de bestelstap samen. Aanbiedingen en bundels maken deel uit van die verkoopflow.', tags: ['Landingspagina’s', 'Aanbod & bundels'], link: '/landing-pages' },
    { title: 'De route naar aankoop afmaken.', body: 'Retargeting sluit aan op de eerste interesse. De focus blijft op de volledige online verkoopflow: van ontdekking naar een concrete aankoop.', tags: ['Retargeting', 'Ecommerce'], link: '/ecommerce-conversie' },
  ] : [
    { title: 'Attention that fits the product.', body: 'Meta Ads and conversion-focused content introduce Pinacello to potential buyers. The product, the occasion and the offer provide a consistent thread.', tags: ['Meta Ads', 'Organic content'], link: '/meta-ads' },
    { title: 'A page that makes the choice clear.', body: 'Campaign landing pages connect the offer, product information and ordering step. Offers and bundles are part of that sales journey.', tags: ['Landing pages', 'Offers & bundles'], link: '/landing-pages' },
    { title: 'Complete the path to purchase.', body: 'Retargeting builds on that first interest. The focus stays on the full online sales journey: from discovery to an actual purchase.', tags: ['Retargeting', 'Ecommerce'], link: '/ecommerce-conversie' },
  ]
  return <div className="pinacello-case">
    <Seo title={nl ? 'Pinacello case: +120% online omzet' : 'Pinacello case: +120% online revenue'} description={c.summary[lang]} path="/cases/pinacello" />
    <header className="pina-case-hero pina-case-wrap">
      <Breadcrumbs items={[{ label: 'Cases', href: '/cases' }, { label: 'Pinacello' }]} />
      <div className="pina-case-heading">
        <div><p className="pina-eyebrow">PINACELLO / ECOMMERCE</p><h1>{nl ? 'Van aandacht' : 'From attention'}<br />{nl ? 'naar ' : 'to '}<em>{nl ? 'aankoop.' : 'purchase.'}</em></h1><p className="pina-case-lead">{nl ? 'Een herkenbaar product. Een helder aanbod. Een digitale klantreis die alles met elkaar verbindt. Voor Pinacello komen campagnes, content en ecommerce samen.' : 'A distinctive product. A clear offer. A digital customer journey that connects it all. For Pinacello, campaigns, content and ecommerce work together.'}</p><a href="#pinacello-aanpak" className="pina-text-link">{nl ? 'Ontdek de aanpak' : 'Explore the approach'} <span aria-hidden="true">↓</span></a></div>
        <aside className="pina-result-card" aria-label={nl ? 'Resultaat van de case' : 'Case result'}><span className="pina-eyebrow">{nl ? 'Het resultaat' : 'The result'}</span><strong>+120<span>%</span></strong><p>{nl ? 'groei in online omzet' : 'growth in online revenue'}</p><div><span aria-hidden="true">↗</span><span>{nl ? 'Campagnes, landingspagina’s en conversie binnen één ecommerce-aanpak.' : 'Campaigns, landing pages and conversion within one ecommerce approach.'}</span></div></aside>
      </div>
      <dl className="pina-project-meta"><div><dt>{nl ? 'Merk' : 'Brand'}</dt><dd>Pinacello</dd></div><div><dt>{nl ? 'Bijdrage' : 'Contribution'}</dt><dd>Stef Keppens</dd></div><div><dt>Focus</dt><dd>Meta Ads · Content · Ecommerce</dd></div><div><dt>Status</dt><dd>{nl ? 'Doorlopende samenwerking' : 'Ongoing collaboration'}</dd></div></dl>
    </header>
    <figure className="pina-showcase pina-case-wrap">
      <div className="pina-browser-bar"><span aria-hidden="true">● ● ●</span><span>Pinacello / {nl ? 'campagne-landingspagina' : 'campaign landing page'}</span><span aria-hidden="true">↗</span></div>
      <a href={c.liveUrl} target="_blank" rel="noopener noreferrer" aria-label={nl ? 'Bekijk de Pinacello-website in een nieuw tabblad' : 'View the Pinacello website in a new tab'}><ResponsiveImage src={c.image} width="1900" height="1024" fetchPriority="high" alt={nl ? 'Pinacello-landingspagina met productbeelden, aanbod en een directe bestelknop' : 'Pinacello landing page with product imagery, offer and a direct order button'} /></a>
      <figcaption><span>{nl ? 'Van merkbeleving naar een duidelijke bestelstap.' : 'From brand experience to a clear ordering step.'}</span><a className="pina-text-link" href={c.liveUrl} target="_blank" rel="noopener noreferrer">{nl ? 'Bekijk de website' : 'View the website'} ↗</a></figcaption>
    </figure>
    <section className="pina-case-wrap pina-context" aria-labelledby="pina-challenge"><div><p className="pina-eyebrow">01 / {nl ? 'De uitdaging' : 'The challenge'}</p><h2 id="pina-challenge">{nl ? 'Aandacht is pas het begin.' : 'Attention is only the beginning.'}</h2></div><div><p>{c.situation[lang]}</p><p>{c.challenge[lang]}</p><div className="pina-objective"><span>{nl ? 'De opdracht' : 'The objective'}</span><strong>{c.objective[lang]}</strong></div></div></section>
    <section className="pina-approach" id="pinacello-aanpak" aria-labelledby="pina-approach-title"><div className="pina-case-wrap"><div className="pina-section-heading"><p className="pina-eyebrow">02 / {nl ? 'De aanpak' : 'The approach'}</p><h2 id="pina-approach-title">{nl ? 'Drie schakels. Eén klantreis.' : 'Three steps. One customer journey.'}</h2><p>{nl ? 'Het werk van Stef Keppens aan de digitale groei van Pinacello verbindt de campagne met wat er na de klik gebeurt.' : 'Stef Keppens’ work on Pinacello’s digital growth connects each campaign with what happens after the click.'}</p></div><div className="pina-step-grid">{steps.map((step, index) => <article className="pina-step" key={step.link}><span className="pina-step-number">0{index + 1}<span aria-hidden="true">↗</span></span><h3>{step.title}</h3><p>{step.body}</p><div className="pina-step-tags">{step.tags.map(tag => <span key={tag}>{tag}</span>)}</div><Link to={step.link}>{nl ? 'Meer over deze aanpak' : 'More about this approach'} ↗</Link></article>)}</div></div></section>
    <section className="pina-case-wrap pina-video-section" aria-labelledby="pina-content-title"><div className="pina-video-copy"><p className="pina-eyebrow">03 / {nl ? 'Content die verkoopt' : 'Content that sells'}</p><h2 id="pina-content-title">{nl ? 'Eén organische video.' : 'One organic video.'}<br /><em>{nl ? '20 verkopen.' : '20 sales.'}</em></h2><p>{nl ? 'Naast betaalde campagnes speelt organische content een rol. Deze video leverde 20 verkopen op: een concreet resultaat van content rond het product.' : 'Organic content plays a role alongside paid campaigns. This video generated 20 sales: a concrete result from product-focused content.'}</p><p className="pina-video-note">{nl ? 'Bekijk de originele video. De video start alleen wanneer je op afspelen drukt.' : 'Watch the original video. Playback starts only when you press play.'}</p><div className="pina-content-tags"><span>{nl ? 'Organische content' : 'Organic content'}</span><span>{nl ? 'Productverhaal' : 'Product story'}</span></div></div><figure className="pina-video-frame"><video controls playsInline preload="metadata" src={c.video} aria-label={nl ? 'Originele organische Pinacello-video' : 'Original organic Pinacello video'} /><figcaption>{nl ? 'Pinacello — de organische video uit deze case.' : 'Pinacello — the organic video from this case.'}</figcaption></figure></section>
    <section className="pina-takeaway"><div className="pina-case-wrap"><p className="pina-eyebrow">04 / {nl ? 'Het resultaat' : 'The result'}</p><h2>{nl ? 'Een sterke campagne stopt niet bij de klik.' : 'A strong campaign goes beyond the click.'}</h2><p>{nl ? 'Pinacello behaalde +120% online omzetgroei. De aanpak brengt aandacht, aanbod en aankoop samen: precies de samenhang waar we ook bij andere ecommerce-bedrijven naar zoeken.' : 'Pinacello achieved +120% growth in online revenue. The approach connects attention, offer and purchase: the same connection we look for in other ecommerce businesses.'}</p><div className="pina-result-summary"><span><strong>+120%</strong>{nl ? 'online omzet' : 'online revenue'}</span><span><strong>20</strong>{nl ? 'verkopen uit één organische video' : 'sales from one organic video'}</span><span><strong>{nl ? 'Doorlopend' : 'Ongoing'}</strong>{nl ? 'werken aan digitale groei' : 'work on digital growth'}</span></div></div></section>
    <CaseEvidence project={c} />
    <section className="pina-case-wrap pina-case-cta"><p className="pina-eyebrow">{nl ? 'Jouw volgende stap' : 'Your next step'}</p><h2>{nl ? 'Waar laat jouw webshop kansen liggen?' : 'Where could your webshop do more?'}</h2><p>{nl ? 'We bekijken je aanbod, campagnes en bestelroute. Samen bepalen we waar de grootste kans zit en welke aanpak past.' : 'We look at your offer, campaigns and ordering journey. Together, we identify the biggest opportunity and the right approach.'}</p><div><Link className="button-dark" to="/contact" onClick={() => trackEvent('audit_cta_clicked', { placement: 'case_pinacello' })}>{nl ? 'Bespreek je webshop' : 'Discuss your webshop'} ↗</Link><Link className="pina-text-link" to="/cases">{nl ? 'Bekijk andere cases' : 'Explore other cases'} ↗</Link></div></section>
  </div>
}
