import type { CaseStudy } from '../data/types'
import { useLang } from '../i18n/LanguageContext'
const context = {
 pinacello:{nl:'De campagne-landingspagina en de originele productvideo tonen de gebruikte verkooproute en content. Het gepubliceerde resultaat is +120% online omzet en 20 verkopen uit één organische video. De meetperiode, vergelijkingsbasis en attributiemethode zijn hier nog niet gepubliceerd; de cijfers zijn daardoor niet onafhankelijk te reconstrueren vanuit deze pagina.',en:'The campaign landing page and original product video show the sales journey and content used. The published results are +120% online revenue and 20 sales from one organic video. The reporting period, comparison baseline and attribution method are not yet published here, so these figures cannot be independently reconstructed from this page.'},
 nooms:{nl:'Nooms is een eigen merk van Stef. Het ontwerp en de website laten zien hoe merk, productaanbod en vervolgstappen verbonden zijn. Een uitverkochte pre-sale gaat over de beschikbare voorraad voor die lancering. Voorraadaantal, verkoopperiode en omzet zijn hier niet gepubliceerd; dit resultaat zegt op zichzelf niets over structurele winst of herhaalaankopen.',en:'Nooms is Stef’s own brand. The design and website show how the brand, product offer and next steps connect. A sold-out presale refers to the stock available for that launch. Stock quantity, sales period and revenue are not published here; this result alone does not establish ongoing profit or repeat purchases.'},
 olearys:{nl:'De bijdrage richt zich op aparte routes voor particuliere bezoekers en zakelijke organisatoren. Een boeking en een offerteaanvraag zijn verschillende conversies. We presenteren de structuur en het werk aan de klantreis; er staat nog geen gevalideerde procentuele groei op deze case.',en:'The contribution focuses on separate journeys for individual visitors and business organisers. A booking and a quotation request are different conversions. This case presents the structure and customer journey work; it does not yet report validated percentage growth.'},
 'e-kart':{nl:'De case beschrijft het werk aan digitale groei voor particuliere rijders en zakelijke groepen in Gent. Meer klanten en boekingen is het doel, geen gemeten resultaat dat we hier al claimen. De bijdrage en doelgroepkeuzes staan hierboven beschreven.',en:'This case describes digital growth work for individual drivers and business groups in Ghent. More customers and bookings is the objective, not a measured result claimed here. The contribution and audience choices are described above.'},
}
export default function CaseEvidence({project}:{project:CaseStudy}) {
 const {lang}=useLang();const nl=lang==='nl'
 return <section className="border-y border-line bg-surface/30" aria-labelledby={`evidence-${project.slug}`}><div className="mx-auto max-w-4xl px-5 py-12 sm:px-8">
  <p className="text-xs uppercase tracking-widest text-mute">{nl?'Werk & resultaatcontext':'Work & result context'}</p>
  <h2 id={`evidence-${project.slug}`} className="mt-3 font-display text-2xl text-paper">{nl?'Wat deze case laat zien':'What this case demonstrates'}</h2>
  <p className="mt-5 max-w-3xl leading-8 text-bone">{context[project.slug][lang]}</p>
  {project.liveUrl && <p className="mt-5 text-sm leading-7 text-mute"><a className="text-paper underline underline-offset-4" href={project.liveUrl} target="_blank" rel="noopener noreferrer">{nl?`Bekijk het publieke werk bij ${project.name}`:`View the public work at ${project.name}`}</a><br/>{nl?'De live website kan intussen gewijzigd zijn. Ze toont het aanbod en de ervaring, niet de achterliggende omzetrapportage.':'The live website may have changed. It shows the offer and experience, not the underlying revenue report.'}</p>}
 </div></section>
}
